name = "dinkleberg"
description = "The Zola theme for nilslice.xyz"
license = "MIT"
homepage = "https://github.com/nilslice/dinkleberg"
min_version = "0.4.0"
demo = "https://nilslice.xyz"

[author]
name = "Steve Manuel"
homepage = "https://github.com/nilslice"

[original]
name = "Guilherme Diego"
homepage = "https://github.com/guidiego"
